### ISSUE TITLE
Foreman 1.4 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#141]
Tasks:
- [x] mod_auth_kerb #3312
- [x] Chef #3699 (partially, will be expanded into a full section)
- [x] proxy SSH puppetrun #3047
- [x] proxy Salt puppetrun #3732
- [x] proxy custom command #3936
- [x] update Rails console docs to use foreman-rake console #3347
- [x] db:seed #3752
- [x] libvirt/dnsmasq providers #3943
- [x] REMOTE_USER attrs(?) #3528
- [x] mysql/mysql2
- [x] Fedora 18 gone
- [x] Hammer CLI release notes
- [x] Debian plugin installation instructions
- [x] RHSCL
- [x] compute profiles #3178
- [x] Swedish
- [x] Link all issue numbers
- [x] Contributors list
- [x] Sprint 19 release notes
- [x] update installer options
- [x] update Foreman settings section
- [x] fix refs to 1.3 in API section
- [ ] update Hammer success story examples
- [ ] SLES provisioning #3733
- [ ] FreeBSD provisioning #2572
- [x] headline features
- [x] installer module changes from sprint 18, 19
- [x] installer requirement for Puppet 2.7
- [x] API doc refresh
- [x] Menu redesign, update references to "More"
- [x] User data support
- [x] Remove user/role cycle upgrade note, bumped to 1.5
- [x] Upgrade instructions/section is 1.2 to 1.3
- [x] proxy dnscmd provider
- [ ] APIv2 spec, error responses

**Comment by mmoll** [comment]
I guess this can get closed? :)

**Comment by domcleal** [comment]
@mmoll I've left them open when there are still incomplete items.. maybe we could migrate the incomplete items to new issues and it may be easier for people to contribute then?

**Comment by mmoll** [comment]
:+1: for single issues

**Comment by domcleal** [comment]
#315, #316, #317
