### ISSUE TITLE
Foreman 1.5 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#176]
Being worked on in _includes/manuals/1.5/.

Tasks:
- [x] #4197 moved ~foreman/config/settings.plugins.d/ to /etc/foreman/plugins/ which will break some RPM upgrades (dir changing to symlink), so users should backup and restore plugin configs before/after upgrades
- [x] oVirt image support (set "Image ID" to the UUID of the image, finish template etc)
- [x] Installer plugin and compute resource support (#3308)
- [ ] Inherited orgs/locs (#3912)
- [x] Avatar/LDAP info (#3827) 
- [x] Upgrade notes on the new auth system (#812)
- [x] libvirt image support (#4123)
- [x] Hammer config file location change (#4792)
- [x] Taxonomy from Puppet run settings (#3214)
- [x] oVirt upgrade notes on SSL verification (#4555)
- [x] new fact upload settings on node.rb (parallel, watch)
- [x] update installer options (closer to final)
- [x] Link all issue numbers
- [x] Contributors list
- [x] Config groups

**Comment by mmoll** [comment]
I guess this can get closed? :)

**Comment by domcleal** [comment]
#318
