### ISSUE TITLE
Foreman 1.8 manual 

### ISSUE THREAD

**Issue by stbenjam** [theforeman/theforeman.org#307]
- [x] Setting name changes in #8484: `restrict_registered_puppetmasters` and `require_ssl_puppetmasters` are now `restrict_registered_smart_proxies`, and `require_ssl_smart_proxies`, respectively
- [x] Headline features #355
- [x] Main release notes
- [x] Settings
- [x] Installer options
- [x] Contributors list
- [x] Translator contributors
- [x] Installer module release notes
- [x] Smart proxy configuration change: enable now supports http/https
- [x] foreman-ec2 package
- [x] foreman-debug package
- [ ] CoreOS provisioning (#368)
- [x] Increased scope of ignore_puppet_facts_for_provisioning (#9104)
- [x] New smart proxy configuration options
- [ ] Multi-NIC support, explanation of provision/primary interfaces, mapping to CRs  (#367)
- [ ] Configuring static versus DHCP boot modes (#367)
- [ ] User data support for VMware (#369)

**Comment by domcleal** [comment]
Closing, 80/20 rule.  The outstanding topics have new tickets or PRs open.
