### ISSUE TITLE
Foreman 1.9 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#366]
Usual stuff:
- [x] Headline features
- [x] Itemised release notes (@domcleal)
  - http://projects.theforeman.org/projects/foreman/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=c&f%5B%5D=release_id&op%5Brelease_id%5D=%3D&v%5Brelease_id%5D%5B%5D=35&f%5B%5D=&c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=subject&c%5B%5D=category&c%5B%5D=closed_on&group_by=
- [x] Foreman setting changes
- [x] Smart proxy setting changes
- [x] Installer options refresh
- [x] Contributors list (@domcleal)
- [x] Translator contributors (@domcleal)
- [x] Installer module release notes

1.9 specifics:
- [x] BMC: rubyipmi 0.10.0 changed the default IPMI driver to "lan20" which may stop it working on older hardware models
- [x] #10167 - API unversioned default changed from v1 to v2
- [x] #8566 - settings categories reorganised
- [x] Remove Chef smart proxy config chapter (renumbering, will affect realms doc link in Foreman)
- [x] Remove umask warning in foreman-installer docs
- [x] Logging configuration (http://projects.theforeman.org/projects/foreman/wiki/Troubleshooting#How-do-I-enable-debugging)
- [x] #10703 - console port now randomised, ensure full range is open in firewall rules
- [x] #10284 - support page now needs foreman-debug's -u option for 1.9
- [x] #1213, #1510 - add audit and build notification messages to email management chapter

**Comment by dLobatog** [comment]
https://github.com/theforeman/theforeman.org/pull/393

**Comment by domcleal** [comment]
All completed.
