### ISSUE TITLE
Foreman 1.11 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#494]
Usual stuff:
- [x] Headline features
- [x] Headline feature screencasts
- [x] Itemised release notes (#544, @domcleal)
- [x] Foreman setting changes
- [x] Smart proxy setting changes
- [x] Installer options refresh
- [x] Contributors list
- [x] Translator contributors
- [x] Installer module release notes
- [x] API documentation per README

1.11 specifics:
- [x] No installer support for Puppet 2.7, #490
- [x] #12671 - PassengerRuby change for Ubuntu 14.04 (Trusty) users
- [x] #6007 - smart class parameters hidden value feature (#543, @orrabin)
- [x] from source assets precompilation should be done in RAILS_ENV=production
- [x] #7228 - RPM (EL) users must have rh-ruby22/rh-ror41 collections available
- [x] #7229 - Fedora 19 references change to 21
- [x] Change Rails 3 reference in from source upgrade docs to Rails 4, or delete it
- [x] #13298 - SSH provisioning now uses /tmp
- [ ] Refresh screenshots due to UI framework change
- [x] #10369 - installer answers file moved from /etc/foreman to /etc/foreman-installer
- [x] #12715 - smart proxy's logs.yml config file/module
- [x] Deprecation of Ubuntu 12.04, Debian 7

**Comment by agx** [comment]
A doc update for #13298 is at: https://github.com/theforeman/theforeman.org/pull/529 (for 0.10.x though)

**Comment by domcleal** [comment]
_includes/manuals/1.11 is now in place, we can start.

**Comment by domcleal** [comment]
Almost all complete, I refiled the screenshots item as #582.
