### ISSUE TITLE
Move websites to HTTPS

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#539]
This is a task list for things that need moving to HTTPS across the website and related bits.  In a week or so's time, we [should have HTTPS available](https://github.com/theforeman/foreman-infra/pull/211) for all sites hosted on the main web server (this website repo, apt and yum repos) but we need to update links and instructions to point to it.  Eventually we can redirect HTTP too.
- [x] Enable HTTPS on web server
- [x] Ensure no mixed content on theforeman.org, e.g. iframes, CSS/JS from external sources (introduction.md uses an iframe to http://slideshare.net for example): #541
- [x] Change apt GPG key download to HTTPS, aka #240: #616
- [ ] ~~Change apt repo URLs to HTTPS~~
- [x] Change yum foreman-release.rpm download to HTTPS: #616
- [ ] Change foreman-release .repo files to HTTPS
- [ ] Change yum repo references in the manual to HTTPS
- [x] Change puppet-foreman repo URLs to HTTPS
- [x] Redirect http://theforeman.org to HTTPS
- [ ] ~~Redirect http://deb.theforeman.org to HTTPS~~
- [ ] Redirect http://yum.theforeman.org to HTTPS

**Comment by ekohl** [comment]
Debian doesn't install apt-transport-https by default so that may be something to be aware of. https://qa.debian.org/popcon.php?package=apt says 6.84% has it installed.

**Comment by domcleal** [comment]
Good to know.  I don't think there's a huge benefit to retrieving the packages themselves over HTTPS, so we don't have to do that.  The main thing is to get the initial GPG key over secure transport, which is downloaded directly from deb.theforeman.org for apt, and from a direct foreman-release.rpm download for yum.

**Comment by ekohl** [comment]
I agree so I'd make them both available allowing users to choose, but wouldn't implement the Debian redirect.

**Comment by lzap** [comment]
For the record, I've moved my blog (hosted via github pages) to
CloudFlare CDN and I am very happy. They provide SSL for free and there
are various setups possible including SSL termination and HTTP or HTTPS
with invalid certificate as a followup.

https://lukas.zapletalovi.com/2015/12/served-by-cloudflare.html

It provides also great statistics and other optimizations.

## 

Later,
 Lukas #lzap Zapletal

**Comment by domcleal** [comment]
> Enable HTTPS on web server

Now enabled on all vhosts, we can work through the other tasks.

**Comment by domcleal** [comment]
All GPG key downloads are switched to HTTPS, as is the website with a redirect. I'm going to close this and not move the package downloads to require or recommend HTTPS for the meantime.
