### ISSUE TITLE
Foreman 1.12 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#555]
Usual stuff:
- [x] Headline features
- [ ] Headline feature screencasts
- [x] Itemised release notes
- [x] Foreman setting changes (#626)
- [x] Smart proxy setting changes
  - [x] #13737 - smart proxy ssl_disabled_ciphers configuration
  - [x] #13667 - all puppet config files and setting names changed (#624)
- [x] Installer options refresh
- [x] Contributors list
- [x] Translator contributors
- [x] Installer module release notes
- [x] API documentation per README

1.12 specifics:
- [x] #9425 - default user role removed
- [x] #14102 - org/loc in ENC YAML changed to full title from name
- [x] #14575 - domain in ENC YAML changed to domain from description
- [x] #14368 - foreman-rackspace/openstack packages in compute resources section, plus upgrade notes to install them if used (#625)
- [x] #14190 - hostgroup_name now shows name, not title in host API responses
- [x] #13761 - smart proxy virsh provider is now two separate dns/dhcp_libvirt providers (@lzap, see #599)
- [x] Ubuntu 12.04 (Precise), Debian 7 (Wheezy) packages no longer available, OS upgrade required (partially #614)
- [x] #14788 - Ubuntu 16.04 (Xenial) support (#614)
- [x] #14809 - Fedora 24, not 21 (#614)
- [x] #8447 - Puppet 4 support (#617)
  - [x] compatibility table
  - [x] external repos, PC1 is an option instead of the main PL repo
  - [x] installation/quickstart - recommend using PC1
  - [x] system requirements, at least 3GB of RAM is required with PC1/Puppet Server
  - [x] update references to modulepaths in /etc/puppet/, which may be /etc/puppetlabs/code under AIO
- [x] #13667 - smart proxy for Puppet 4.0+ requires resource_type API permission (see https://github.com/theforeman/puppet-puppet/pull/388/files)  (#624)
- [x] List EL6 as a deprecated OS (#614)
- [x] #8884 - min Ruby version for Foreman is 2.0.0 (source installation section)
- [x] #12912 - replace RHSCL, softwarecollections.org instructions for SCLorg repo (#618)

**Comment by tbrisker** [comment]
- [x]  [#13896](http://projects.theforeman.org/issues/13896) - Anonymous role was renamed to Default role

**Comment by angystardust** [comment]
- [x] #3582 - Allow Subnets to have Parameters like Domains

**Comment by tbrisker** [comment]
- [x] Update smart proxy default ciphers and disabling ciphers option - https://github.com/theforeman/smart-proxy/pull/380#issuecomment-200331462

**Comment by domcleal** [comment]
Docs copied from 1.11 to 1.12, we can start this now.

**Comment by aoyawale** [comment]
do you guys create the manuals in other languages? if so how can I contribute?

**Comment by domcleal** [comment]
@chagara no, we don't, sorry!
