### ISSUE TITLE
Foreman 1.13 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#649]
Usual stuff:
- [x] Headline features
- [ ] Headline feature screencasts
- [x] Itemised release notes
- [x] Foreman setting changes
- [x] Smart proxy setting changes
- [x] Installer options refresh
- [x] Contributors list
- [x] Translator contributors
- [x] Installer module release notes
- [x] API documentation per README

1.13 specifics:
- [x] remove EL6 from supported OSes (quickstart, packages sections, upgrade)
- [x] #12364 - source install/upgrade instructions require `rake webpack:compile` and npm dependency/npm install
- [ ] #12634 - PXE loader is now an option (somewhere in unattended installation sections)
- [x] #4528 - Facter 2+ structured facts supported, in Puppet compatibility section
- [x] Puppet compatibility of installer is now 3.6+, defaulting to Puppet Server 2.6
- [x] Ubuntu 14.04 requires Puppet Labs repos (Puppet >= 3.6)
- [x] Remove v8314 references from SCL section, no longer a dependency
- [x] PuppetDB integration in installer is Puppet 4/AIO only (#691)
- [ ] IPv6 subnets and addressing modes in 4.4.7

**Comment by domcleal** [comment]
Outstanding tasks filed as #766 and #767.
