### ISSUE TITLE
Foreman 1.14 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#708]
Usual stuff:
- [x] Headline features
- [x] Headline feature screencasts
- [x] Itemised release notes
- [x] Foreman setting changes
- [x] Smart proxy setting changes
- [x] Installer options refresh
- [x] Contributors list
- [x] Translator contributors
- [x] Installer module release notes
- [x] API documentation per README
- [x] List all new deprecation warnings
- [x] Update Puppet compatibility matrix

1.14 specifics:
- [x] Min Ruby version for smart proxy is 2.0.0
- [x] Document 'audit' logger
- [x] #6372 - LDAP authentication imports orgs/locs on account creation
- [x] #16207 - custom hiera settings for installer (https://github.com/theforeman/foreman-installer/pull/204)
- [x] ssh bmc provider (https://github.com/theforeman/theforeman.org/pull/721/files)
- [x] #7766 - MS DHCP provider uses API instead of netsh (update netsh references, use "bundle exec")
- [x] #7167 Settings Auth tab was renamed to Authentication, it's mentioned in the manual several times
- [x] cover https://github.com/theforeman/foreman/pull/3984#issuecomment-261513971 in release notes
- [x] #17487 - API supports using _session_id for subsequent requests
- [x] #12156 - email configuration is preferably via Settings not email.yaml
- [x] #17340 - list IPv6 addressing support for Rackspace
- [x] #16167 - refer to template form's Help tab for allowed helpers
- [x] #13936 - add supported browser list

**Comment by lzap** [comment]
Added https://github.com/theforeman/theforeman.org/pull/721/files

**Comment by ares** [comment]
I added one more item to 1.14 specifics, Setting Auth tab was renamed to Authentication

**Comment by domcleal** [comment]
1.14 manual now copied & can be edited.

**Comment by dLobatog** [comment]
Linked the LDAP & taxonomies checkbox with https://github.com/theforeman/theforeman.org/pull/771

**Comment by domcleal** [comment]
Tasks complete, please file anything else as a new PR or issue.
