### ISSUE TITLE
Foreman 1.15 manual

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#765]
Usual stuff:
- [x] Headline features
- [ ] Headline feature screencasts
- [x] Itemised release notes
- [x] Foreman setting changes
- [x] Smart proxy setting changes
- [x] Installer options refresh
- [x] Contributors list
- [x] Translator contributors
- [ ] Installer module release notes
- [x] API documentation per README - https://github.com/theforeman/theforeman.org/pull/857
- [ ] List all new deprecation warnings
- [x] Update Puppet compatibility matrix

1.15 specifics:
- [x] #17500 - realm smart module configuration changes - https://github.com/theforeman/theforeman.org/pull/856
- [ ] #17015 - compute resource key pair management
- [x] #16982 - scope properly when taxonomies are not set
- [ ] #18001 - default roles are locked, upgrade renames them if they were modified
- [ ] #20271 - document how to modify .each(&:some) to .each { |i| i.some } in all templates, smart class parameters (default values), smart class parameter overrides (values), parameters, an example to be found at https://github.com/theforeman/community-templates/pull/407

**Comment by dLobatog** [comment]
@domcleal Where do you get the combined committers + translators list?

**Comment by domcleal** [comment]
Translaters are listed at the top of the PO files by year (i.e. only 2017 translators).

**Comment by domcleal** [comment]
> List all new deprecation warnings

Unticked this again, I don't see that any of the new (1.17) deprecations have been documented.

**Comment by dLobatog** [comment]
I thought this would prosper https://github.com/theforeman/foreman/pull/4219 and I wouldn't have to document these as deprecations. I don't think it's going to be a good idea to force people to update all their templates for such little benefit - I'll wait until before 1.15.0 final to document these (which are all of the new deprecations).

I'll  raise the topic again in https://groups.google.com/forum/?fromgroups#!topic/foreman-dev/P364HozAYZA

**Comment by domcleal** [comment]
> [..] (which are all of the new deprecations).

Host::Managed#to_ip_address and the seed audit_modified? method were also deprecated.

**Comment by alexjfisher** [comment]
Release notes aren't rendering correctly on the website (indentation is wrong).
Looks fine it GitHub https://github.com/theforeman/theforeman.org/blob/gh-pages/_includes/manuals/1.15/1.2_release_notes.md but not [here](https://www.theforeman.org/manuals/1.15/index.html#Releasenotesfor1.15)

I'm guessing the raw markdown is missing some blank lines, (but have no real way of testing).

Update - Fixed in https://github.com/theforeman/theforeman.org/commit/97dddd3efc3c83fcd40ba042be8cbe279b933596

**Comment by GregSutcliffe** [comment]
I have no idea why this is still open... closing :)
