### ISSUE TITLE
Foreman 1.16 manual

### ISSUE THREAD

**Issue by dLobatog** [theforeman/theforeman.org#903]
Usual stuff:
- [x] Headline features https://github.com/theforeman/theforeman.org/pull/962
- [ ] Headline feature screencasts
- [x] Itemised release notes
- [x] Foreman setting changes
- [x] Smart proxy setting changes
- [x] Installer options refresh
- [x] Contributors list
- [x] Translator contributors
- [ ] Installer module release notes
- [x] API documentation per README 
- [x] List all new deprecation warnings
- [x] Update Puppet compatibility matrix (#994)
- [x] make Puppet 4.x requirement for the installer more prominent (#994)

1.16 specifics

- [ ] #20271 - document how to modify .each(&:some) to .each { |i| i.some } in all templates, smart class parameters (default values), smart class parameter overrides (values), parameters, an example to be found at https://github.com/theforeman/community-templates/pull/407

Feel free to edit and add any 1.16 specifics

**Comment by cjacobs-at-comscore** [comment]
'make Puppet 4.x requirement for the installer more prominent' - specially for 'foreman-installer', otherwise other installation methods are just fine?

**Comment by GregSutcliffe** [comment]
Pretty sure we can close this now that 1.16 is out (and out of support :P)
